# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chenchich
email: andrewbanchich@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the wedding website of Andrew and Ju Yi (soon to be) Banchich.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chenchich.us" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


# Multilingual config
t:
  English:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/"
    thebigday:
      name: "The Big Day"
      url: "/the-big-day/"
    weddingparty:
      name: "Wedding Party"
      url: "/wedding-party/"
    weddingweek:
      name: "Wedding Week"
      url: "/wedding-week/"
    itinerary:
      name: "Itinerary"
      url: "/itinerary/"
    accommodations:
      name: "Accommodations"
      url: "/accommodations/"
    rsvp:
      name: "R.S.V.P."
      url: "/rsvp/"
    taiwantrip:
      name: "Taiwan/Hong Kong 2017"
      url: "/taiwan-hong-kong-2017/"
    contact:
      name: "Contact Us"
      url: "/contact-us/"
  中文 (台灣):
    home:
      name: "首頁"
      url: "/首頁/"
    about:
      name: "關於我們"
      url: "/關於我們/"
    thebigday:
      name: "囍宴當日"
      url: "/囍宴當日/"
    weddingparty:
      name: "陪嫁團"
      url: "/陪嫁團/"
    weddingweek:
      name: "甜蜜婚禮周"
      url: "/甜蜜婚禮周/"
    itinerary:
      name: "行程"
      url: "/行程/"
    accommodations:
      name: "住宿"
      url: "/住宿/"
    rsvp:
      name: "喜帖回函"
      url: "/喜帖回函/"
    taiwantrip:
      name: "2017臺灣/香港見"
      url: "/2017臺灣香港見/"
    contact:
      name: "聯絡我們"
      url: "/聯絡我們/"
